module.exports = {
	content: ["./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		screens: {
			xxs: "320px",
			xss: "400px",
			xs: "480px",
			sm: "640px",
			md: "768px",
			"md-large": "890px",
			lg: "1024px",
			"xl-small": "1200px",
			xl: "1280px",
			xxl: "1320px",
			"2xl": "1441px",
			"3xl": "1920px",
			"4xl": "2560px",
			"tiny-laptop": { raw: "(min-width: 1280px) and (max-height: 740px)" },
			laptop: { raw: "(min-width: 1024px) and (max-height: 835px)" },
			"min-h-md": { raw: "(min-height: 800px)" },
			"min-h-xl": { raw: "(min-height: 1080px)" },
		},
		extend: {
			colors: {
				transparent: "transparent",
				current: "currentColor",
				cobalt: "#0047FF",
				electric: "#DBF2FF",
				stone: "#D3DADD",
				ketchup: "#F23428",
				sand: "#F3FFC7",
				candy: "#FFD2FD",
				boost: "#5800C8",
				energy: "#D3FFD2",
				forest: "#00A72F",
			},
			fontFamily: {
				heading: ["PSTElliots", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				body: ["PSTElliots", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				gridular: ["Gridular", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				nippo: ["Nippo", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				become: ["Become", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				haltwins: ["HALTwins", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				recoleta: ["Recoleta", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
				pilowlava: ["Pilowlava", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji"],
			},
		},
	},
	plugins: [require("@tailwindcss/typography"), require("@tailwindcss/aspect-ratio"), require("@tailwindcss/forms")],
};
